<?php

return [
    [
        'roles' => 'Super User|Admin',
        'permissions' => 'contact.index',
        'name' => 'Contact',
        'route' => 'cms.contact.index',
        'icon' => 'fas fa-phone',
        'table' => 'contacts',
        'sidebar' => true,
        'subMenus' => [],
    ],
    [
        'roles' => 'Super User|Admin',
        'permissions' => 'article.index',
        'name' => 'Article',
        'route' => 'cms.article.index',
        'icon' => 'fas fa-newspaper',
        'table' => 'articles',
        'sidebar' => true,
        'subMenus' => [],
    ],
    [
        'roles' => 'Super User|Admin',
        'permissions' => 'gallery.index',
        'name' => 'Gallery',
        'route' => 'cms.gallery.index',
        'icon' => 'fas fa-images',
        'table' => 'galleries',
        'sidebar' => true,
        'subMenus' => [],
    ],
    [
        'roles' => 'Super User|Admin',
        'permissions' => 'career.index',
        'name' => 'Career',
        'route' => 'cms.career.index',
        'icon' => 'fas fa-briefcase',
        'table' => 'careers',
        'sidebar' => true,
        'subMenus' => [],
    ],
    [
        'roles' => 'Super User|Admin',
        'permissions' => 'career-benefit.index',
        'name' => 'Career Benefit',
        'route' => 'cms.career-benefit.index',
        'icon' => 'fas fa-briefcase',
        'table' => 'career_benefits',
        'sidebar' => true,
        'subMenus' => [],
    ],
    [
        'roles' => 'Super User|Admin',
        'permissions' => 'faq.index',
        'name' => 'FAQ',
        'route' => 'cms.faq.index',
        'icon' => 'fas fa-question',
        'table' => 'faqs',
        'sidebar' => true,
        'subMenus' => [],
    ],
    [
        'roles' => 'Super User',
        'permissions' => 'configuration.index',
        'name' => 'Configuration',
        'route' => 'cms.configuration.index',
        'icon' => 'fas fa-gears',
        'table' => null,
        'sidebar' => true,
        'subMenus' => [
            [
                'roles' => 'Super User',
                'permissions' => 'configuration.index',
                'name' => 'Configuration',
                'route' => 'cms.configuration.index',
                'icon' => 'fas fa-gears',
                'table' => null,
                'sidebar' => false,
            ],
            [
                'roles' => 'Super User',
                'permissions' => 'activity.index',
                'name' => 'Activity',
                'route' => 'cms.configuration.activity',
                'icon' => 'fas fa-history',
                'table' => 'activity_log',
                'sidebar' => true,
            ],
            [
                'roles' => 'Super User',
                'permissions' => 'user.index',
                'name' => 'User',
                'route' => 'cms.configuration.user.index',
                'icon' => 'fas fa-user',
                'table' => 'users',
                'sidebar' => true,
            ],
            [
                'roles' => 'Super User',
                'permissions' => 'role.index',
                'name' => 'Role',
                'route' => 'cms.configuration.role.index',
                'icon' => 'fas fa-briefcase',
                'table' => 'roles',
                'sidebar' => true,
            ],
            [
                'roles' => 'Super User',
                'permissions' => 'permission.index',
                'name' => 'Permission',
                'route' => 'cms.configuration.permission.index',
                'icon' => 'fas fa-key',
                'table' => 'permissions',
                'sidebar' => true,
            ],
            [
                'roles' => 'Super User',
                'permissions' => 'setting.index',
                'name' => 'Setting',
                'route' => 'cms.configuration.setting.index',
                'icon' => 'fas fa-gear',
                'table' => 'settings',
                'sidebar' => true,
            ],
        ],
    ],
];
